[project]
name = "python-lib-dev"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "fastapi[all]>=0.124.4",
    "orjson>=3.11.5",
]
